services:
  kali:
    image: kali-lab
    cap_add:
      - NET_ADMIN
      - NET_RAW
    hostname: kali-lab
    restart: unless-stopped
    container_name: kali-lab
    tty: true
    stdin_open: true
    networks:
      lab_net:
        ipv4_address: 10.50.0.10

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/24
          gateway: 10.50.0.1