services:
  kali-lab01:
    image: kali-lab
    cap_add:
      - NET_ADMIN
      - NET_RAW
    hostname: kali-lab-01
    restart: unless-stopped
    container_name: kali-lab-01
    tty: true
    stdin_open: true
    networks:
      lab_net:
        ipv4_address: 10.25.18.20
    

  metasploitable-lab01:
    image: tleemcjr/metasploitable2:latest
    restart: unless-stopped
    container_name: metasploitable-lab-01
    tty: true
    stdin_open: true
    networks:
      lab_net:
        ipv4_address: 10.25.18.10

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.25.18.0/24
          gateway: 10.25.18.1