server {
listen 80;     
server_name www.videobox.nl;     
return 301 https://$host$request_uri; }  

server {
listen 443 ssl; 
server_name www.videobox.nl;
ssl_certificate     /etc/nginx/certs/videobox.crt;     
ssl_certificate_key /etc/nginx/certs/videobox.key;      
ssl_protocols TLSv1.2 TLSv1.3; 
ssl_ciphers         
HIGH:!aNULL:!MD5;   
root /usr/share/nginx/html;    
index index.html;      
location / {         try_files $uri $uri/ =404;     } }
